In [185]:
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
#import cartopy.crs as ccrs

In [186]:
#DS1 = xr.open_dataset('1951_1960.nc')
#df1 = DS1.to_dataframe() #empty


#DS2 = xr.open_dataset('1961_1970.nc')
#df2 = DS2.to_dataframe() #empty

DS3 = xr.open_dataset('1971_1980.nc')
df3 = DS3.to_dataframe()

DS4 = xr.open_dataset('1981_1990.nc')
df4 = DS4.to_dataframe()

DS5 = xr.open_dataset('1991_2000.nc')
df5 = DS5.to_dataframe()

DS6 = xr.open_dataset('2001_2010.nc')
df6 = DS6.to_dataframe()

DS7 = xr.open_dataset('2011_2019.nc')
df7 = DS7.to_dataframe()

In [84]:
fulldf=pd.concat([df3, df4, df5, df6, df7])
fulldf1=np.nan_to_num(fulldf)

DS=xr.merge([DS3,DS4,DS5,DS6,DS7])
fulldf2=DS.to_dataframe()



In [85]:
DSp=DS.precip
#DSp["ONI index"]=oni
len(DSp.lon)

144

In [179]:
oni=pd.read_csv('onijja.csv', header=None)
type(oni)
a=np.array(oni)
a=a.reshape(49)
#len(oni)

b=np.repeat(a, 10368)
oni3d=b.reshape(49,72,144)


In [181]:

lon=DS1.coords['lon'].values
lat=DS1.coords['lat'].values
year=np.arange(1971,2020)
len(year)
ONI =xr.DataArray(
data=oni3d,
dims=["year","lat","lon"],
coords=[year,lat,lon]          
        )

In [182]:
ONI.coords


Coordinates:
  * year     (year) int64 1971 1972 1973 1974 1975 ... 2015 2016 2017 2018 2019
  * lat      (lat) float64 88.75 86.25 83.75 81.25 ... -83.75 -86.25 -88.75
  * lon      (lon) float64 -178.8 -176.2 -173.8 -171.2 ... 173.8 176.2 178.8

In [188]:
DS2= DS['precip']
DS1 = DS2[DS2.time.dt.season == ['JJA']]
ds=DS1.groupby("time.year").sum("time")
print(ds.coords)

Coordinates:
  * lon      (lon) float64 -178.8 -176.2 -173.8 -171.2 ... 173.8 176.2 178.8
  * lat      (lat) float64 88.75 86.25 83.75 81.25 ... -83.75 -86.25 -88.75
  * year     (year) int64 1971 1972 1973 1974 1975 ... 2015 2016 2017 2018 2019


/Users/sakshilabhane/anaconda3/lib/python3.7/site-packages/xarray/core/nanops.py:140: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


In [184]:
#x=xr.merge(ONI, ds)
ONI_DS=ONI.to_dataset(name="ONI_Index")
Precip_DS=ds.to_dataset(name="Precip")
final_DS=Precip_DS.merge(ONI_DS)
print(final_DS)

<xarray.Dataset>
Dimensions:    (lat: 72, lon: 144, year: 49)
Coordinates:
  * lon        (lon) float64 -178.8 -176.2 -173.8 -171.2 ... 173.8 176.2 178.8
  * lat        (lat) float64 88.75 86.25 83.75 81.25 ... -83.75 -86.25 -88.75
  * year       (year) int64 1971 1972 1973 1974 1975 ... 2016 2017 2018 2019
Data variables:
    Precip     (year, lat, lon) float32 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    ONI_Index  (year, lat, lon) float64 -0.8 -0.8 -0.8 -0.8 ... 0.3 0.3 0.3 0.3


In [187]:
xr.corr(ONI_DS, Precip_DS, dim="year")
xr.corr(final_DS)

AttributeError: module 'xarray' has no attribute 'corr'

In [87]:
precip = fulldf['precip']
np.isnan(precip).sum()   #3957240 (65% NaN values)

3957240

In [98]:
clim = DS['precip'].groupby('time.season').mean('time', keep_attrs = True)
type(clim)

xarray.core.dataarray.DataArray

In [74]:
da = DS.precip
mi=6 
mf=8
i=0

year_avg = [0] * 48

In [77]:
for year in range(1971,2019):
    i= year-1971
    timei = str(year) + "-0" + str(mi) + "-01"
    timef = str(year)+ "-0" + str(mf) + "-01"
    
    temp_da = da.sel(time=slice(timei,timef))
    temp_df = temp_da.to_dataframe()
    temp_df = temp_df.mean()

    year_avg[i] = temp_df.mean()


    
len(year_avg)    #global


#clim = fulldf['precip'].mean() #what


48

In [38]:
clim = DS['precip'].groupby('time.season').mean('time', keep_attrs = True)
    
#clim.data = clim.data * 86400
#clim.attrs['units'] = 'mm/day'
    
fig = plt.figure(figsize=[12,5])
ax= fig.add_subplot(111, projection=ccrs.PlateCarree(central_longitute=180 ))
clim.plot.contourf(ax=ax,
                   levels=np.arange(0, 13.5, 1.5),
                   extend='max',
                   transform=ccrs.PlateCarree(),
                   cbar_kwargs={'label': clim.units})
ax.coastlines()
plt.show()

NameError: name 'ccrs' is not defined

<Figure size 864x360 with 0 Axes>

In [88]:
precip = DS['precip']

ppt1 = precip[precip.time.dt.season == ['JJA']]

ppt1 = np.nan_to_num(ppt1.data.ravel())
#len(ppt1[ppt1!=0])

AttributeError: 'numpy.ndarray' object has no attribute 'coords'

In [18]:
precip.coords

Coordinates:
  * lon      (lon) float64 -178.8 -176.2 -173.8 -171.2 ... 173.8 176.2 178.8
  * lat      (lat) float64 88.75 86.25 83.75 81.25 ... -83.75 -86.25 -88.75
  * time     (time) datetime64[ns] 2011-01-01 2011-02-01 ... 2019-12-01

In [21]:
precip.time

<xarray.DataArray 'time' (time: 108)>
array(['2011-01-01T00:00:00.000000000', '2011-02-01T00:00:00.000000000',
       '2011-03-01T00:00:00.000000000', '2011-04-01T00:00:00.000000000',
       '2011-05-01T00:00:00.000000000', '2011-06-01T00:00:00.000000000',
       '2011-07-01T00:00:00.000000000', '2011-08-01T00:00:00.000000000',
       '2011-09-01T00:00:00.000000000', '2011-10-01T00:00:00.000000000',
       '2011-11-01T00:00:00.000000000', '2011-12-01T00:00:00.000000000',
       '2012-01-01T00:00:00.000000000', '2012-02-01T00:00:00.000000000',
       '2012-03-01T00:00:00.000000000', '2012-04-01T00:00:00.000000000',
       '2012-05-01T00:00:00.000000000', '2012-06-01T00:00:00.000000000',
       '2012-07-01T00:00:00.000000000', '2012-08-01T00:00:00.000000000',
       '2012-09-01T00:00:00.000000000', '2012-10-01T00:00:00.000000000',
       '2012-11-01T00:00:00.000000000', '2012-12-01T00:00:00.000000000',
       '2013-01-01T00:00:00.000000000', '2013-02-01T00:00:00.000000000',
       '2013-03-01T00:00:00.000000000', '2013-04-01T00:00:00.000000000',
       '2013-05-01T00:00:00.000000000', '2013-06-01T00:00:00.000000000',
       '2013-07-01T00:00:00.000000000', '2013-08-01T00:00:00.000000000',
       '2013-09-01T00:00:00.000000000', '2013-10-01T00:00:00.000000000',
       '2013-11-01T00:00:00.000000000', '2013-12-01T00:00:00.000000000',
       '2014-01-01T00:00:00.000000000', '2014-02-01T00:00:00.000000000',
       '2014-03-01T00:00:00.000000000', '2014-04-01T00:00:00.000000000',
       '2014-05-01T00:00:00.000000000', '2014-06-01T00:00:00.000000000',
       '2014-07-01T00:00:00.000000000', '2014-08-01T00:00:00.000000000',
       '2014-09-01T00:00:00.000000000', '2014-10-01T00:00:00.000000000',
       '2014-11-01T00:00:00.000000000', '2014-12-01T00:00:00.000000000',
       '2015-01-01T00:00:00.000000000', '2015-02-01T00:00:00.000000000',
       '2015-03-01T00:00:00.000000000', '2015-04-01T00:00:00.000000000',
       '2015-05-01T00:00:00.000000000', '2015-06-01T00:00:00.000000000',
       '2015-07-01T00:00:00.000000000', '2015-08-01T00:00:00.000000000',
       '2015-09-01T00:00:00.000000000', '2015-10-01T00:00:00.000000000',
       '2015-11-01T00:00:00.000000000', '2015-12-01T00:00:00.000000000',
       '2016-01-01T00:00:00.000000000', '2016-02-01T00:00:00.000000000',
       '2016-03-01T00:00:00.000000000', '2016-04-01T00:00:00.000000000',
       '2016-05-01T00:00:00.000000000', '2016-06-01T00:00:00.000000000',
       '2016-07-01T00:00:00.000000000', '2016-08-01T00:00:00.000000000',
       '2016-09-01T00:00:00.000000000', '2016-10-01T00:00:00.000000000',
       '2016-11-01T00:00:00.000000000', '2016-12-01T00:00:00.000000000',
       '2017-01-01T00:00:00.000000000', '2017-02-01T00:00:00.000000000',
       '2017-03-01T00:00:00.000000000', '2017-04-01T00:00:00.000000000',
       '2017-05-01T00:00:00.000000000', '2017-06-01T00:00:00.000000000',
       '2017-07-01T00:00:00.000000000', '2017-08-01T00:00:00.000000000',
       '2017-09-01T00:00:00.000000000', '2017-10-01T00:00:00.000000000',
       '2017-11-01T00:00:00.000000000', '2017-12-01T00:00:00.000000000',
       '2018-01-01T00:00:00.000000000', '2018-02-01T00:00:00.000000000',
       '2018-03-01T00:00:00.000000000', '2018-04-01T00:00:00.000000000',
       '2018-05-01T00:00:00.000000000', '2018-06-01T00:00:00.000000000',
       '2018-07-01T00:00:00.000000000', '2018-08-01T00:00:00.000000000',
       '2018-09-01T00:00:00.000000000', '2018-10-01T00:00:00.000000000',
       '2018-11-01T00:00:00.000000000', '2018-12-01T00:00:00.000000000',
       '2019-01-01T00:00:00.000000000', '2019-02-01T00:00:00.000000000',
       '2019-03-01T00:00:00.000000000', '2019-04-01T00:00:00.000000000',
       '2019-05-01T00:00:00.000000000', '2019-06-01T00:00:00.000000000',
       '2019-07-01T00:00:00.000000000', '2019-08-01T00:00:00.000000000',
       '2019-09-01T00:00:00.000000000', '2019-10-01T00:00:00.000000000',
       '2019-11-01T00:00:00.000000000', '2019-12-01T00:00:00.000000000'],
      dtype='dateti

In [41]:
ppt1 = precip[precip.time.dt.season == ['JJA']]

In [80]:
type(ppt1)

numpy.ndarray

In [64]:
np.isnan(ppt1.data.ravel()).sum()

181710

In [65]:
len(ppt1.data.ravel())

279936

In [76]:
ppt1[ppt1 !=0.0]

array([  6.85,   6.66,   6.45, ..., 128.97, 127.37, 117.54], dtype=float32)

In [72]:
ppt1.sum()

7793534.5

In [48]:
ds = da = xr.open_dataset("C:/Users/dutts/Documents/oni_ppt_corr/data/full_data_monthly_v2020_2001_2010_25.nc")

In [49]:
precip = ds['precip']

In [53]:
ppt2 = precip[precip.time.dt.season == ['JJA']]

In [55]:
ppt2.data

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       ...,

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan

In [61]:
np.isnan(ppt2.data.ravel()).sum()

201900

In [62]:
len(ppt2.data.ravel())

311040

In [73]:
ppt2 = np.nan_to_num(ppt2.data.ravel())

In [75]:
ppt2[ppt2 !=0.0]

array([ 16.05,  16.  ,  16.57, ..., 136.91, 136.78, 135.92], dtype=float32)

In [77]:
ppt2.sum()

8661594.0

In [40]:
jupyter notebook --ip 10.191.12.23 --port 8888

SyntaxError: invalid syntax (<ipython-input-40-dd331fd7608e>, line 1)